config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :groups
  resources :posts
  resources :activities do 
    member do
      post :save
    end
    member do
      get :reflect
    end
    member do
      get :receive
    end
    member do
      get :respond
    end
    collection do
      get :selected
    end
  resources :activities
  end

  root 'posts#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all.order(:track)
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def edit
  	@activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to activities_path
    else
      render 'new'
    end 
  end

  def update
  	@activity = Activity.find(params[:id])

  	if @activity.update(activity_params)
  		redirect_to activities_path
    else
    	render 'edit'
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    redirect_to activities_path
  end

  def save
    @activity = Activity.find(params[:id])

    if @activity.update(:select == TRUE)
      flash[:notice] = "Activities successfully saved!"
      redirect_to activities_path
    else
      flash[:alert] = "There was an error choosing activities. Please try again." 
    end
  end

  def selected
    @activities = Activity.where(:select == TRUE).order(:track)
  end

  def receive
    @activity = Activity.find(params[:id])
  end

  def reflect
    @activity = Activity.find(params[:id])
  end

  def respond
    @activity = Activity.find(params[:id])
  end

  private
    def activity_params
    	params.require(:activity).permit(:track, :title, :receive_content, :reflect_content, :respond_content, :select)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end
  
  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
  	@group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end 
  end

  def update
  	@group = Group.find(params[:id])

  	if @group.update(group_params)
  		redirect_to groups_path
    else
    	render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  private
    def group_params
    	params.require(:group).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all.reverse
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end 
  end

  def update
  	@post = Post.find(params[:id])

  	if @post.update(post_params)
  		redirect_to posts_path
    else
    	render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
    def post_params
    	params.require(:post).permit(:title, :instructions, :content)
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity do |f| %>
 
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@activity.errors.count, "error") %> prohibited
        this activity from being saved:
      </h2>
      <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :track %><br>
    <%= f.text_field :track %>
  </p>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :receive_content %><br>
    <%= f.text_area :receive_content %>
  </p>

  <p>
    <%= f.label :reflect_content %><br>
    <%= f.text_area :reflect_content %>
  </p>

  <p>
    <%= f.label :respond_content %><br>
    <%= f.text_area :respond_content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Activities</h1>
<p>
	Select the activities that you would like your students to see on their personal pages. 
	You can also create your own track with activities. Select "new activities" and fill in the content in the boxes that appear. 
</p>

<p>
<table class="table table-bordered table-scrollable">
	<tr>
		<th>Select</th>
		<th>Track</th>
		<th>Title</th>
		<th>Receive Content</th>
		<th>Reflect Content</th>
		<th>Respond Content</th>
	</tr>

    <% @activities.each do |activity| %>
     <tr>
    	<td><%= check_box_tag(activity.select, checked = true) %></td>
    	<td><%= activity.track %></td>
    	<td><%= activity.title %></td>
    	<td><%= activity.receive_content %></td>
    	<td><%= activity.reflect_content %></td>
    	<td><%= activity.respond_content %></td>
    	<td><%= link_to 'Show', activity_path(activity) %></td>
    	<td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    	<td><%= link_to 'Delete', activity_path(activity), method: :delete, data: { confirm: 'Are you sure?' } %></br>
     </tr>
   <% end %>
</table>
<br>
<%= button_to 'Save' %><br>
<%= link_to 'Create a New Activity', new_activity_path %></br>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/receive.html.erb
<h1>Receive Content</h1>

<h1><%= @activity.title %></h1>
<p>from the <%=@activity.track %> track</p> 

<h2><%= @activity.receive_content %></h2>

<%= link_to 'Next', reflect_activity_path %></br>
<%= link_to 'Back', activity_path %></br>
<%= link_to 'Home', posts_path %>

app/views/activities/reflect.html.erb
<h1>Reflect Content</h1>

<h1><%= @activity.title %></h1>
<p>from the <%=@activity.track %> track</p> 

<h2><%= @activity.reflect_content %></h2>

<%= link_to 'Next', respond_activity_path %></br>
<%= link_to 'Back', receive_activity_path %></br>
<%= link_to 'Home', posts_path %>

app/views/activities/respond.html.erb
<h1>Respond Content</h1>

<h1><%= @activity.title %></h1>
<p>from the <%=@activity.track %> track</p> 

<h2><%= @activity.respond_content %></h2>

<%= link_to 'New Post', new_post_path %></br>
<%= link_to 'Back', reflect_activity_path %></br>
<%= link_to 'Home', posts_path %>

app/views/activities/selected.html.erb
<h1>Selected Activities</h1>

<table>
	<tr>
      <th>Track Name</th>
	  <th>Activity Title</th>
	</tr>

  <% @activities.each do |activity| %>
    <tr>
      <td><%= activity.track %></td>
      <td><%= activity.title %></td>
      <td><%= link_to 'Begin Activity', activity_path(activity) %>
    </tr>
  <% end %>
 </table>

 <%= link_to 'Back', posts_path %>

app/views/activities/show.html.erb
<h1><%= @activity.title %></h1>
<p>from the <%=@activity.track %> track</p> 

<%= link_to 'Next', receive_activity_path %></br>
<%= link_to 'Back', selected_activities_path %></br>
<%= link_to 'Home', posts_path %>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
 
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<table>
  <% @groups.each do |group| %>
  <tr>
  	<td><%= group.name %></td>
  	<td><%= link_to 'Edit', edit_group_path(group)%></td>
  	<td><%= link_to 'Delete', group_path(group), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New', new_group_path %>

app/views/groups/new.html.erb
<h1>Add A New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Welcome to your wall!</h1>

<%= link_to 'Complete Next Activity', selected_activities_path %></br>
<br>
<%= link_to 'New Post', new_post_path %></br>
<br>

<% @posts.each do |post| %>
  <strong><%= post.title %></strong></br>
  <%= post.content %></br>
  Posted <%= time_ago_in_words(post.created_at) %> ago</br>
  <%= link_to 'Edit', edit_post_path(post) %> <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></br>
<br>
<% end %>

app/views/posts/new.html.erb
<h1>Create a New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>